apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: april-16 
  janus-idp.io/tekton: april-16
  backstage.io/kubernetes-id: april-16
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: april-16
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  