apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: april-16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: april-16 
  name: april-16
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: april-16
    weight: 100 
