apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: april-16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: april-16 
  name: april-16
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: april-16 
